#!/usr/bin/env node

/**
 * Kobo Dashboard Screenshot Service
 * Reads calendar.json (generated by calendar_processor.py) and creates screenshots
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import express from 'express';
import puppeteer from 'puppeteer';
import dotenv from 'dotenv';

// ES module compatibility
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config();

const PORT = process.env.PORT || 3333;
const CALENDAR_JSON = process.env.CALENDAR_JSON_PATH || './calendar.json';
const SCREENSHOT_INTERVAL_MINUTES = parseInt(process.env.SCREENSHOT_INTERVAL_MINUTES || '6');
const SCREENSHOT_WIDTH = parseInt(process.env.SCREENSHOT_WIDTH || '1680');
const SCREENSHOT_HEIGHT = parseInt(process.env.SCREENSHOT_HEIGHT || '1264');

function log(message) {
  const timestamp = new Date().toISOString();
  console.log(`[${timestamp}] ${message}`);
}

class ScreenshotService {
  constructor() {
    this.browser = null;
    this.isGenerating = false;
  }

  async initialize() {
    log('Initializing Screenshot Service...');
    
    // Launch browser
    this.browser = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--no-first-run',
        '--no-zygote',
        '--disable-gpu'
      ]
    });
    
    log('Browser initialized');
  }

  async checkCalendarFile() {
    /**
     * Check if calendar.json exists and is recent
     */
    try {
      if (!fs.existsSync(CALENDAR_JSON)) {
        log('Warning: calendar.json not found. Make sure calendar_processor.py is running.');
        return false;
      }
      
      const stats = fs.statSync(CALENDAR_JSON);
      const ageMinutes = (Date.now() - stats.mtime.getTime()) / (1000 * 60);
      
      if (ageMinutes > 10) {
        log(`Warning: calendar.json is ${ageMinutes.toFixed(1)} minutes old. Calendar processor might not be running.`);
      }
      
      return true;
    } catch (error) {
      log(`Error checking calendar file: ${error.message}`);
      return false;
    }
  }

  async generateScreenshot() {
    if (this.isGenerating) {
      log('Screenshot generation already in progress, skipping...');
      return;
    }

    this.isGenerating = true;
    
    try {
      log('Starting screenshot generation...');
      
      // Check if calendar data is available
      if (!await this.checkCalendarFile()) {
        // Create empty calendar.json if it doesn't exist
        const emptyEvents = [];
        fs.writeFileSync(CALENDAR_JSON, JSON.stringify(emptyEvents, null, 2));
        log('Created empty calendar.json file');
      }
      
      const page = await this.browser.newPage();
      
      // Set viewport
      await page.setViewport({ 
        width: SCREENSHOT_WIDTH, 
        height: SCREENSHOT_HEIGHT, 
        deviceScaleFactor: 1 
      });
      
      // Navigate to the dashboard
      await page.goto(`http://localhost:${PORT}`, { 
        waitUntil: 'networkidle0',
        timeout: 30000 
      });
      
      // Wait a bit for any dynamic content to load
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Take screenshot
      await page.screenshot({
        path: path.join(__dirname, 'today.png'),
        fullPage: false
      });
      
      await page.close();
      
      log('Screenshot saved to today.png');
      
    } catch (error) {
      log(`Error generating screenshot: ${error.message}`);
    } finally {
      this.isGenerating = false;
    }
  }

  async startScheduledScreenshots() {
    // Generate initial screenshot
    await this.generateScreenshot();
    
    // Schedule regular screenshots
    const intervalMs = SCREENSHOT_INTERVAL_MINUTES * 60 * 1000;
    setInterval(async () => {
      await this.generateScreenshot();
    }, intervalMs);
    
    log(`Screenshot generation scheduled every ${SCREENSHOT_INTERVAL_MINUTES} minutes`);
  }

  async cleanup() {
    if (this.browser) {
      await this.browser.close();
      log('Browser closed');
    }
  }
}

async function setupExpressServer() {
  const app = express();
  
  // Serve static files
  app.use(express.static(__dirname));
  
  // API endpoint to get calendar data
  app.get('/api/calendar', (req, res) => {
    try {
      if (fs.existsSync(CALENDAR_JSON)) {
        const calendarData = fs.readFileSync(CALENDAR_JSON, 'utf8');
        res.setHeader('Content-Type', 'application/json');
        res.send(calendarData);
      } else {
        log('Calendar.json not found, returning empty array');
        res.json([]);
      }
    } catch (error) {
      log(`Error serving calendar data: ${error.message}`);
      res.status(500).json({ error: 'Failed to load calendar data' });
    }
  });

  
  // Health check endpoint
  app.get('/health', (req, res) => {
    const calendarExists = fs.existsSync(CALENDAR_JSON);
    const screenshotExists = fs.existsSync(path.join(__dirname, 'today.png'));
    
    res.json({
      status: 'ok',
      calendar_file: calendarExists,
      screenshot_file: screenshotExists,
      timestamp: new Date().toISOString()
    });
  });
  
  // Start server
  app.listen(PORT, '0.0.0.0', () => {
    log(`Dashboard server running on http://0.0.0.0:${PORT}`);
  });
  
  return app;
}

async function main() {
  try {
    log('Starting Kobo Dashboard Screenshot Service...');
    log(`Calendar file: ${CALENDAR_JSON}`);
    log(`Screenshot interval: ${SCREENSHOT_INTERVAL_MINUTES} minutes`);
    log(`Screenshot dimensions: ${SCREENSHOT_WIDTH}x${SCREENSHOT_HEIGHT}`);
    
    // Setup Express server
    await setupExpressServer();
    
    // Initialize screenshot service
    const screenshotService = new ScreenshotService();
    await screenshotService.initialize();
    
    // Start scheduled screenshots
    await screenshotService.startScheduledScreenshots();
    
    log('Screenshot service started. Press Ctrl+C to stop.');
    
    // Graceful shutdown
    process.on('SIGINT', async () => {
      log('Shutting down...');
      await screenshotService.cleanup();
      process.exit(0);
    });
    
    process.on('SIGTERM', async () => {
      log('Shutting down...');
      await screenshotService.cleanup();
      process.exit(0);
    });
    
  } catch (error) {
    log(`Fatal error: ${error.message}`);
    process.exit(1);
  }
}

// Handle uncaught exceptions
process.on('uncaughtException', (error) => {
  log(`Uncaught exception: ${error.message}`);
  process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
  log(`Unhandled rejection at ${promise}: ${reason}`);
  process.exit(1);
});

main();
